name: Analyze ETF Dividend Payment Capacity

on:
  push:
    paths:
      - 'data/twse/dividend/*.csv'

permissions:
  contents: write

jobs:
  analyze-dividend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install fonts
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-noto-cjk fonts-noto-cjk-extra
    
    - name: Run dividend analysis
      run: |
        # 找出所有修改的 CSV 檔案
        if [ "$(git rev-list --count HEAD)" -gt 1 ]; then
          # 如果有前一個提交，比較變更
          for file in $(git diff --name-only HEAD^ HEAD | grep 'data/twse/dividend/.*\.csv$'); do
            stock_symbol=$(basename "$file" .csv)
            python strategy/future_dividend_payment_capacity_strategy.py "$stock_symbol"
          done
        else
          # 如果是第一次提交，處理所有 CSV 檔案
          for file in data/twse/dividend/*.csv; do
            stock_symbol=$(basename "$file" .csv)
            python strategy/future_dividend_payment_capacity_strategy.py "$stock_symbol"
          done
        fi
    
    - name: Check for generated files
      run: |
        echo "Checking for generated files..."
        ls -la report/
        if [ -n "$(ls -A report/future_dividend_payment_capacity_*.png 2>/dev/null)" ]; then
          echo "Found generated files"
        else
          echo "No files matching pattern found"
          exit 0
        fi
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add report/future_dividend_payment_capacity_*.png
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update dividend analysis [skip ci]"
          git push
        fi 